planning_plugin: ompl_interface/OMPLPlanner
start_state_max_bounds_error: 0.1
jiggle_fraction: 0.05
request_adapters: >-
  default_planner_request_adapters/AddTimeOptimalParameterization
  default_planner_request_adapters/ResolveConstraintFrames
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints

planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
  RRTkConfigDefault:
    type: geometric::RRT
    range: 0.0
    goal_bias: 0.05
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1
  PRMkConfigDefault:
    type: geometric::PRM
    range: 0.0
    max_nearest_distance: 100
  PRMstarkConfigDefault:
    type: geometric::PRMstar
    range: 0.0
  ESTkConfigDefault:
    type: geometric::EST
    range: 0.0
    goal_bias: 0.05
  BFMTkConfigDefault:
    type: geometric::BFMT
    range: 0.0
    num_samples: 1000
    num_batch_samples: 100
  LazyPRMkConfigDefault:
    type: geometric::LazyPRM
    range: 0.0
    max_nearest_distance: 100

right_arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTkConfigDefault
    - RRTstarkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - ESTkConfigDefault
    - BFMTkConfigDefault

left_arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTkConfigDefault
    - RRTstarkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - ESTkConfigDefault
    - BFMTkConfigDefault

both_arms:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTkConfigDefault
    - RRTstarkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - LazyPRMkConfigDefault

right_gripper:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTkConfigDefault

left_gripper:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTkConfigDefault
